### ISSUE TITLE
Add permission level to server player entity

### ISSUE THREAD

**Issue by Stupididot69** [SFort/FScript#18]
a simple mode that disables all other conditions besides cheats being on and survival mode present for creative-like flight (and possibly the other two flights) because i don't want to log into my normal survival world and remember i forgot to play without the mod and i can fly
also the mod is very confusing, maybe adding descriptions when you hover the cursor over a button would clear things up

**Comment by SFort** [comment]
if you click the question mark in the top right corner it will popup tooltips.

**Comment by SFort** [comment]
ye sorry this was a minor change but i compleatly forgot about it.
just using "permission_level:1" in your script should do what you want
